<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findLastFive()
    {
        return $this->createQueryBuilder('article')
            ->setMaxResults(5)
            ->orderBy('article.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $param
     *
     * @return mixed
     */
    public function search($param)
    {
        return $this->createQueryBuilder('article')
            ->andWhere('article.title LIKE :param')
            ->orWhere('article.content LIKE :param')
            ->setParameter(':param', '%'.$param.'%')
            ->getQuery()
            ->getResult();
    }

    public function findAllOrdered()
    {
        $qb = $this->createQueryBuilder('article')
            ->addOrderBy('article.createdAt', 'DESC');
        $query = $qb->getQuery();

        return $query->execute();
    }
}
