<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findLastFive()
    {
        return $this->createQueryBuilder('article')
            ->setMaxResults(5)
            ->orderBy('article.publishedAt', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function getRandomOne()
    {
        $max = $this->getEntityManager()
            ->createQuery('SELECT COUNT(a.id) FROM AppBundle:Article a')
            ->getSingleScalarResult();

        $article = $this->createQueryBuilder('article')
            ->andWhere('article.id = :rand')
            ->setParameter('rand', rand(1, $max))
            ->setMaxResults(1)
            ->getQuery()
            ->execute();
        if (!$article) {
            $this->getRandomOne();
        }

        return array_shift($article);
    }
}
