<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function findAllWithUsers()
    {
        return $this->createQueryBuilder('author')
            ->leftJoin('author.user', 'user')
            ->addSelect('user')
            ->getQuery()
            ->execute();
    }
}
