<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAllOrdered()
    {
        return $this->createQueryBuilder('comment')
            ->leftJoin('comment.author', 'author')
            ->addSelect('author')
            ->leftJoin('comment.article', 'article')
            ->addSelect('article')
            ->andWhere('comment.article IS NOT NULL')
            ->addOrderBy('article.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findByAuthor($author)
    {
        return $this->createQueryBuilder('comment')
            ->andWhere('comment.author = :author')
            ->andWhere('comment.article IS NOT NULL')
            ->setParameter('author', $author)
            ->leftJoin('comment.article', 'article')
            ->addSelect('article')
            ->getQuery()
            ->getResult();
    }

    public function findByArticle($article)
    {
        return $this->createQueryBuilder('comment')
            ->andWhere('comment.article = :article')
            ->setParameter(':article', $article)
            ->leftJoin('comment.author', 'author')
            ->addSelect('author')
            ->getQuery()
            ->getResult();
    }
}
