<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findByTag($tag)
    {
        return $this->createQueryBuilder('tag')
            ->andWhere('tag.title = :tag')
            ->setParameter(':tag', $tag)
            ->leftJoin('tag.articles', 'articles')
            ->addSelect('articles')
            ->leftJoin('articles.author', 'author')
            ->addSelect('author')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
